# example netlify.toml
[build]
  command = "./netlify.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18.17.0"
  RUBY_VERSION = "false"
  PYTHON_VERSION = "false"
  GO_VERSION = "false"
  PYTHON_RUNTIME = "false"
  USE_PYTHON = "false"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
